#!/usr/bin/env python3
"""Generate mod/spider_punk_2077/generated/sheets.lua from design/sheets/*.json.

Each sheet row becomes one Lua table (the mod's equivalent of a struct), keyed by the row id.
Refuses to generate while preflight has blocking findings.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "mod" / "spider_punk_2077" / "generated" / "sheets.lua"
SHEET_TABLES = ["abilities", "tuning", "inputs", "hooks", "visuals"]


def lua(value, indent=""):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(float(value)) if isinstance(value, float) else str(value)
    if isinstance(value, str):
        return json.dumps(value)  # JSON string escapes are valid Lua escapes for this content
    if isinstance(value, list):
        return "{" + ", ".join(lua(v) for v in value) + "}"
    if isinstance(value, dict):
        inner = indent + "  "
        parts = [f"{inner}{k} = {lua(v, inner)}," for k, v in value.items()]
        return "{\n" + "\n".join(parts) + f"\n{indent}}}"
    raise TypeError(value)


def main():
    pre = subprocess.run([sys.executable, str(ROOT / "tools" / "preflight.py")], capture_output=True, text=True)
    if pre.returncode != 0:
        sys.stdout.write(pre.stdout)
        sys.exit("gen: preflight has blocking findings; fix the sheets first")

    lines = [
        "-- GENERATED by tools/gen.py from design/sheets/*.json. Do not edit: change the sheet and regenerate.",
        "local S = {}",
    ]
    for name in SHEET_TABLES:
        sheet = json.loads((ROOT / "design" / "sheets" / f"{name}.json").read_text())
        lines.append(f"\nS.{name} = {{}}")
        for row in sheet["rows"]:
            fields = {k: v for k, v in row.items()}
            lines.append(f"S.{name}.{row['id']} = {lua(fields)}")
    lines.append("\nreturn S\n")
    OUT.write_text("\n".join(lines))
    print(f"gen: wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
